apiVersion: v1
kind: Service
metadata:
  name: container-app-service
spec:
  selector:
    app: container-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
